[CUBRIDQA-608] refine script for version

diff --git a/CTP/common/script/run_cubrid_install b/CTP/common/script/run_cubrid_install
--- a/CTP/common/script/run_cubrid_install
+++ b/CTP/common/script/run_cubrid_install
@@ -371,16 +371,14 @@ function InstallBuildForCoverage()
 
 function needDevToolSet()
 {
-    buildNum=$1
-    buildNumberWithoutSuffix=`echo $buildNum|grep -Pom 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,7}'`
-    major=`echo $buildNumberWithoutSuffix|awk -F '.' '{print $1}'`
-    minor=`echo $buildNumberWithoutSuffix|awk -F '.' '{print $2}'`    
-    prefixNumber=${major}${minor}
-    if [ $prefixNumber -ge 102 ];then
+    version=$1
+    major_version=$(echo $version | cut -d . -f 1)
+    minor_version=$(echo $version | cut -d . -f 2)
+    if [ $major_version -ge 10 -a $minor_version -ge 2 ];then
 	echo true
     else
 	echo false
-    fi	
+    fi 
 
 }
 
@@ -410,20 +408,27 @@ function BuildAndInstallForUnitTest()
     tar -zvxf $buildFile 
     cp -rf ${buildName}/* $cub/  
     cd $cub
+    if [ -f VERSION ]; then
+    	version_file=VERSION
+    elif [ -f VERSION-DIST ]; then
+    	version_file=VERSION-DIST
+    fi
+    version=$(cat $version_file)
   
-    cmakeParams="Debug"
+    configure_options="-DCMAKE_BUILD_TYPE=Debug"
     if [ "$tCat" == "unit-release" ];then
-	cmakeParams="RelWithDebInfo"
+	configure_options="-DCMAKE_BUILD_TYPE=RelWithDebInfo"
     fi
     	 
-    if [ "`needDevToolSet ${buildName}`" == "true" ];then
+    if [ "`needDevToolSet ${version}`" == "true" ];then
+	[ -f "/opt/rh/devtoolset-6/enable" ] && echo "[Error]: devtoolset-6 is not found" && exit 1
 	(
 	  source /opt/rh/devtoolset-6/enable
-	  cmake -DCMAKE_BUILD_TYPE=${cmakeParams}
+	  cmake ${configure_options}
           make -j
 	)
     else
-	  cmake -DCMAKE_BUILD_TYPE=${cmakeParams}
+	  cmake ${configure_options}
           make -j
     fi 
     
