[CUBRIDQA-73] add coverage script (#289)
* [CUBRIDQA-73] add coverage script

* [CUBRIDQA-72] refine coverage script to read user info from coverage.conf

* [CUBRIDQA-73] fix run_cubrid_install to support coverage testing

* [CUBRIDQA-73] refine run_coverage to support backup and preparation for testing

diff --git a/CTP/common/script/run_cubrid_install b/CTP/common/script/run_cubrid_install
--- a/CTP/common/script/run_cubrid_install
+++ b/CTP/common/script/run_cubrid_install
@@ -302,34 +302,73 @@ function InstallBuildForCoverage()
     build_url=$1
     source_url=$2
     buildFile=${build_url##*/}
-    cub="CUBRID"
     curDir=`pwd`
+    cub_folder_name="CUBRID"
     goToInstallationDirectory
+    cubrid service stop >/dev/null 2>&1
     echo ""
     echo "=====install CUBRID $buildFile =========="
     echo ""
-    srcFolder=`echo $buildFile|awk -F '-' '{print $2}'`
-    rm $buildFile >/dev/null 2>&1
-    cubrid service stop >/dev/null 2>&1
-    wget -t 3 -T 120 $build_url
-    if [ -d $cub ]
-    then
-            rm -rf CUBRID
+    if [ -f "$buildFile" ];then
+	rm $buildFile >/dev/null 2>&1
+    fi
+  
+    if [ -d "$cub_folder_name" ];then
+	rm -rf $cub_folder_name
+        mkdir -p $cub_folder_name 
+    else
+	mkdir -p $cub_folder_name
     fi
 
+    cd $cub_folder_name
+    wget -t 3 -T 120 $build_url
+    if [ $? -ne 0 ]
+    then
+	echo ""
+        echo "[ERROR]: Please confirm the build url ${build_url}"
+	exit -1
+    fi
+    
     tar zvxfm $buildFile
-
+    cd -
     mkdir -p build
     cd build
-    sourceFile=${source_url##*/}
-    rm -rf "cubrid-${srcFolder}" >/dev/null 2>&1
-    rm $sourceFile >/dev/null 2>&1
-    wget -t 3 -T 120 $source_url
-    tar zvxfm $sourceFile
-    rm src
-    ln -s "cubrid-${srcFolder}/src"
+    cov_source_file_name=${source_url##*/}
+    build_main_number=`echo $cov_source_file_name|awk -F '-' '{print $2}'`
+    build_prefix="${build_main_number%.*}"
+    branch_src_folder="cubrid-${build_prefix}"
+    build_src_folder_full_name="${cov_source_file_name%-gcov*}" 
+	
+    if [ ! -d "$branch_src_folder" ];then
+	mkdir -p $branch_src_folder
+    fi
 
-    rm $sourceFile
+    cd $branch_src_folder
+    if [ -f "$cov_source_file_name" ];then
+	rm $cov_source_file_name  >/dev/null 2>&1
+    fi
+
+    if [ -d "$build_src_folder_full_name" ];then
+        rm -rf $build_src_folder_full_name
+	mkdir -p $build_src_folder_full_name
+    else
+	mkdir -p $build_src_folder_full_name
+    fi
+
+    cd $build_src_folder_full_name
+    wget -t 3 -T 120 $source_url
+    if [ $? -ne 0 ];then
+	echo ""
+	echo "[ERROR] Please confirm the coverage source build url ${source_url}"
+	exit -1
+    fi
+
+    
+    if [ -f "$cov_source_file_name" ];then
+    	tar zvxfm $cov_source_file_name
+    	rm $cov_source_file_name
+    fi
+
     checkEnvironmentVariable
     cd $curDir
     echo INSTALL `date '+%Y%m%d%H%M%s'` $@ >> $HOME/.qacoverage
